###################### default configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL = "https://theapplicationlab.github.io/theapplicationlab/"

# Title of your website (required).
title = "The Application Lab"

# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Europe/London"
# post pagination
pagerSize = 12 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

########################## Permalinks ############################
[permalinks.page]
"pages" = "/:slug/"


############################# Modules ############################
[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
#[[build.cachebusters]]
#source = 'assets/watching/hugo_stats\.json'
#target = 'style\.css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = 'js'
[[build.cachebusters]]
source = 'assets/.*\.(css|scss|sass)'
target = 'css'
[[build.cachebusters]]
source = 'data/.*\.(.*)$'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ############################
[outputs]
home = ["HTML", "RSS", "videoSitemap", "SearchIndex"]
section = ["HTML", "RSS"] # Add this line
############################# Imaging ############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "Lanczos"

############################ Caches ##############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[markup.highlight]
style = 'github-dark' # see https://xyproto.github.io/splash/docs/all.html

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true


########################### Media types ###########################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]


########################### Output Format ##########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[outputFormats.videoSitemap]
mediaType = "application/xml"
baseName = "video-sitemap"
isPlainText = false
notAlternative = true


############################# Plugins ##############################

# JS Plugins
[[params.plugins.js]]
link = "plugins/youtube-lite.js"

[sitemap]
filename = 'sitemap.xml'
priority = 0

[Taxonomies]
category = "categories"
author = "authors"

######################### Services ###############################
[services]
[services.rss]
# Number of items to include in the RSS feed.
limit = 20

#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "350px"
logo_height = "54px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "The Application Lab"
# navbar fixed to top
navbar_fixed = true
# theme-mode
theme_switcher = true
theme_default = "light" # available options [light/dark/system]
# Main Sections
mainSections = ["blog","workshops"]
# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
copyright = "© 2025 The Application Lab"

homepageTitle = "The Application Lab"

# Preloader
# preloader module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Join WhatsApp Group"
label_sub = " "
link = "https://chat.whatsapp.com/JgONfqufJQlKl53XPAddIM?mode=ac_t"

# search
[search]
enable = true
primary_color = "#667eea"
include_sections = ["blog", "workshops", "resources", "work-with-us", "/resources/faq/", "/resources/downloadable-resources/"]
show_image = false
show_description = true
show_tags = true
show_categories = true


# seo meta data for OpenGraph / Twitter Card
# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
keywords = ["application lab", "university application", "scholarships"]
description = "The Application Lab is a peer-led mentorship and community initiative dedicated to supporting students from underrepresented and under-resourced backgrounds in navigating international university applications, with a primary focus on the UK."
author = "The Application Lab"
image = "images/og-image.png"


# site verifications
# verification module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies & analytics. By continuing to use this website, you agree to their use."
button = "I Accept"


[[params.plugins.js]]
link = "plugins/lazy-loader.js"
#[[params.plugins.js]]
#link = "plugins/cookie.js"

######################## sidebar widgets #########################
[widgets]
sidebar = []

# Subscription
[subscription]
enable = false
# mailchimp subsciption
#mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&id=a0a2c6d074" # replace this url with yours
#mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
